-- Nox Finance - schema Supabase
-- Cole este arquivo no SQL Editor do Supabase e clique em Run.

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  whatsapp_id text unique not null,
  nome text,
  criado_em timestamptz default now()
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nome text unique not null,
  tipo text not null check (tipo in ('receita', 'despesa', 'transferencia'))
);

create table if not exists public.cartoes_credito (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  nome text not null,
  limite numeric(10,2) default 0,
  dia_vencimento integer,
  dia_fechamento integer,
  ativo boolean default true,
  criado_em timestamptz default now(),
  unique(usuario_id, nome)
);

create table if not exists public.lancamentos (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  valor numeric(10,2) not null,
  categoria text not null,
  descricao text,
  tipo text not null check (tipo in ('receita', 'despesa', 'cartao')),
  forma_pagamento text,
  cartao_id bigint references public.cartoes_credito(id) on delete set null,
  data_lancamento date not null default current_date,
  criado_em timestamptz default now(),
  corrigido_em timestamptz
);

create table if not exists public.parcelamentos (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  descricao text not null,
  tipo text default 'compra' check (tipo in ('compra', 'divida')),
  valor_parcela numeric(10,2) not null,
  total_parcelas integer not null,
  parcelas_pagas integer default 0,
  forma_pagamento text,
  cartao_id bigint references public.cartoes_credito(id) on delete set null,
  categoria text,
  data_inicio date,
  data_fim date,
  status text default 'ativo',
  criado_em timestamptz default now()
);

create table if not exists public.metas (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  categoria text,
  valor_maximo numeric(10,2),
  periodo text default 'mensal'
);

create index if not exists idx_usuarios_whatsapp_id on public.usuarios(whatsapp_id);
create index if not exists idx_lancamentos_usuario on public.lancamentos(usuario_id, criado_em desc);
create index if not exists idx_lancamentos_cartao on public.lancamentos(cartao_id);
create index if not exists idx_cartoes_usuario on public.cartoes_credito(usuario_id, ativo);
create index if not exists idx_parcelamentos_usuario on public.parcelamentos(usuario_id, status, data_fim);

insert into public.categorias (nome, tipo) values
  ('mercado', 'despesa'), ('alimentacao', 'despesa'), ('ifood', 'despesa'),
  ('uber', 'despesa'), ('transporte', 'despesa'), ('luz', 'despesa'),
  ('agua', 'despesa'), ('internet', 'despesa'), ('contas', 'despesa'),
  ('salario', 'receita'), ('freelance', 'receita'), ('extra', 'receita'),
  ('cartao', 'transferencia'), ('credito', 'transferencia'), ('outros', 'despesa'),
  ('lazer', 'despesa'), ('saude', 'despesa'), ('moradia', 'despesa')
on conflict (nome) do update set tipo = excluded.tipo;
