-- Nox Finance - tabela de parcelamentos
-- Cole no SQL Editor do Supabase e clique em Run antes de usar "parcelamentos" no bot.

create table if not exists public.parcelamentos (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  descricao text not null,
  tipo text default 'compra' check (tipo in ('compra', 'divida')),
  valor_parcela numeric(10,2) not null,
  total_parcelas integer not null,
  parcelas_pagas integer default 0,
  forma_pagamento text,
  cartao_id bigint references public.cartoes_credito(id) on delete set null,
  categoria text,
  data_inicio date,
  data_fim date,
  status text default 'ativo',
  criado_em timestamptz default now()
);

create index if not exists idx_parcelamentos_usuario
  on public.parcelamentos(usuario_id, status, data_fim);
